AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 with Security Group - Noor DevOps Project

Parameters:
  KeyName:
    Type: String
    Description: Name of existing EC2 KeyPair
    Default: noor-key

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-070e5bd3ff10324f8   # Ubuntu AMI
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: Noor-CloudFormation-EC2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: Public IP of EC2
    Value: !GetAtt MyEC2Instance.PublicIp