AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket using CloudFormation - Noor DevOps Project 🚀

Parameters:
  BucketName:
    Type: String
    Description: Enter unique S3 bucket name

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

      Tags:
        - Key: Name
          Value: Noor-CloudFormation-Bucket
        - Key: Project
          Value: DevOps-Practice

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadAccess
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${S3Bucket.Arn}/*"

Outputs:
  BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref S3Bucket

  WebsiteURL:
    Description: Static Website URL
    Value: !GetAtt S3Bucket.WebsiteURL